/*
##
##	Enhancer for YouTube™ | Firefox Add-on
##	======================================
##
##	Author: Maxime RF <https://www.mrfdev.com>
##
##	This file is protected by copyright laws and international copyright
##	treaties, as well as other intellectual property laws and treaties.
##
##	All rights not expressly granted to you are retained by the author.
##	Read the license.txt file for more details.
##
##	If it's not enough clear for you Baris Derin, you have no rights to use my work,
##	neither as-is nor modified! Being an AMO Editor doesn't give you that right!
##	Improve your coding logic instead of using others work!
##
##	© MRFDEV.com - All Rights Reserved
##
*/
(function(a){if(!window.EnhancerForYouTube){var E=function(b){n&&"yt-navigate-start"===b.type&&(a.location.href=b.detail.url);clearInterval(ia);clearInterval(P);L=ja=U=!1;v&&(v.style.display="none",w.style.display="none",F&&(clearInterval(V),k.querySelector("i.loop").parentNode.classList.remove("active"),F.hide()));a.body.classList.remove("enhancer-for-youtube-pinned-player");try{if("yt-history-load"===b.type||"yt-navigate-start"===b.type&&"watch"!==b.detail.pageType)ba(),D("default");d.classList.remove("ads-removed")}catch(f){}},
va=function(a){var h;"undefined"===typeof a&&(h=JSON.parse(localStorage.getItem("enhancer-for-youtube")||'{"customtheme":""}'));localStorage.setItem("enhancer-for-youtube",JSON.stringify({customtheme:h?h.customtheme:a,theme:b.theme.replace("-polymer.css",".css"),polymer:!0}))},ka=function(){if(k){for(var a=k.querySelectorAll("li"),f=a.length-1;0<=f;f--)a[f].classList[0<=b.toolbarbuttons.indexOf(a[f].dataset.name)?"remove":"add"]("hidden");k.querySelector('li[data-name="message"]').classList[b.message?
"remove":"add"]("hidden");""!==b.toolbarbuttons||b.message?(v.classList.remove("hidden"),wa()):v.classList.add("hidden")}},Pa=function(){ca();if(0===F[0].children.length){var b=p;F.slider({animate:"slow",range:!0,min:0,max:H,values:[p,x],start:function(a,c){b=p},slide:function(b,c){p=c.values[0];x=c.values[1];ca()},stop:function(a,c){p===H?(p=H-1,la(),ca()):x===p&&(x=p+1,la(),ca());b!==p&&d.seekTo(p)}})}else la();F.show();v.classList.add("extended")},la=function(){F.slider("values",[p,x])},ca=function(){xa[0].textContent=
ma(p)+" / "+ma(x)},ya=function(b){if(b.classList.contains("active"))clearInterval(V),b.classList.remove("active"),F.hide(),v.classList.remove("extended");else{b.classList.add("active");0===$("#enhancer-for-youtube-slider",k).length&&(F=$("<div />").attr("id","enhancer-for-youtube-slider").appendTo(k),xa=$("<div />").addClass("start-end").appendTo(k));H=p=x=!1;var h=0,c=0<a.location.href.indexOf("list=");V=setInterval(function(){try{d&&"function"===typeof d.getPlayerState?H?!c&&d.getCurrentTime()>=
x?d.seekTo(p):c||0!==d.getPlayerState()?(c&&H===x&&2>H-d.getCurrentTime()||c&&H!==x&&d.getCurrentTime()>=x)&&d.seekTo(p):d.playVideo():(H=x=parseInt(d.getDuration(),10),p=0,"undefined"!==typeof ytplayer&&ytplayer.config&&ytplayer.config.args&&(p=ytplayer.config.args.start?parseInt(ytplayer.config.args.start,10):0,x=ytplayer.config.args.end?parseInt(ytplayer.config.args.end,10):x),h=0,Pa()):(h++,M())}catch(e){15<h&&clearInterval(V),d=!1}},1E3)}},ma=function(b){b=Number(b);var a=Math.floor(b/3600),
c=Math.floor(b%3600/60);b=Math.floor(b%3600%60);return(0<a?a+":":"")+(0<c?(0<a&&10>c?"0":"")+c+":":"0:")+(10>b?"0":"")+b},na=function(){a.body.classList.remove("enhancer-for-youtube-pinned-player");a.body.classList.contains("viewport")&&(a.body.classList.remove("viewport"),a.body.classList.add("_viewport_"));window.scrollTo(0,0);a.body.classList.add("enhancer-for-youtube-cinema-mode");b.cinemamodewideplayer&&!a.body.classList.contains("enhancer-for-youtube-wide-player")&&D("large");0<=b.autofocusevents.indexOf("cinema")&&
r()},ba=function(){a.body.classList.remove("enhancer-for-youtube-cinema-mode");!b.wideplayer&&b.cinemamodewideplayer?D("default"):a.body.classList.contains("_viewport_")&&(a.body.classList.remove("_viewport_"),D("large"));0<=b.autofocusevents.indexOf("cinema")&&r()},za=function(a){if(b.controlvolumealtkey&&a.altKey||!b.controlvolumealtkey&&!a.ctrlKey){a.preventDefault();try{var f=d.getVolume();0<a.deltaY?(f-=b.volumevariation,0>f&&(f=0)):(f+=b.volumevariation,100<f&&(f=100),d.isMuted()&&d.unMute());
d.setVolume(f);J.textContent=f;oa();b.defaultvolume&&(b.volume=f);var c=(new Date).getTime();a=0<f?"false":"true";localStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+f+',\\"muted\\":'+a+'}","expiration":'+(c+2592E6)+',"creation":'+c+"}";sessionStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+f+',\\"muted\\":'+a+'}","creation":'+c+"}"}catch(e){}}},Q=function(){var a=[b.quality1,b.quality2,b.quality3,b.quality4],f=setInterval(function(){try{if(d&&"function"===typeof d.getPlayerState||("video"===
A?M():pa()),-1!==d.getPlayerState()){for(var b=0,h=!1,g,k=d.getAvailableQualityLevels();b<a.length&&!h;b++)for(var l in k)if(a[b]===k[l]){h=a[b];break}g=h?h:"auto";g!==d.getPlaybackQuality()?G||(G=!0,d.hasAttribute("flashvars")?(d.pauseVideo(),d.setPlaybackQuality(g),d.playVideo()):d.setPlaybackQuality(g)):g===d.getPlaybackQuality()&&(G=!0,clearInterval(f),clearTimeout(c))}}catch(da){d=!1}},500),c=setTimeout(function(){clearInterval(f)},3E4)},Z=function(h){d||M();if(d&&d.hasAttribute("flashvars")){clearInterval(V);
clearInterval(P);k&&F&&(k.querySelector("i.loop").parentNode.classList.remove("active"),F.hide());var f="ad_module ad2_module ad3_module ad_channel_code_instream ad_channel_code_overlay ad_device ad_eurl ad_flags ad_host ad_host_tier ad_logging_flag ad_preroll ad_slots ad_tag ad_type ad_video_pub_id adsense_video_doc_id advideo aftv afv afv_ad_tag afv_ad_tag_restricted_to_instream afv_invideo_ad_tag afv_inslate_ad_tag afv_instream_max afv_video_min_cpm allow_html5_ads allowed_ads apply_fade_on_midrolls as_launched_in_country baseUrl cafe_experiment_id cc_asr enabled_engage_types excluded_ads dynamic_allocation_ad_tag max_dynamic_allocation_ad_tag_length max_ad_duration ppv_remarketing_url prefetch_ad_live_stream pyv_ad_channel remarketing_url rmktEnabled show_pyv_in_related use_meta_ad_player".split(" "),
c=function(b){for(var a=f.length-1;0<=a;a--)if(b===f[a])return!0;return!1},e=d.getAttribute("flashvars"),B=d.cloneNode(!0);e=e.split("&");for(var q=[],n,m,da=0;da<e.length;da++)n=e[da].split("="),m=n[0],n=n[1],c(m)||q.push(m+"="+n);c=q.join("&");0>c.indexOf("enablejsapi")&&(c+="&enablejsapi=1");0>c.indexOf("iv_load_policy")&&(c+="&iv_load_policy=1");0>c.indexOf("autoplay")&&(c+="&autoplay=1");b.removeannotations&&(c=c.replace("iv_load_policy=1","iv_load_policy=3"));B.setAttribute("flashvars",c);l.textContent=
"";l.appendChild(B);qa(l);G=!1;b.autopausevideos?W():b.selectquality&&Q()}else if(d){if(h||"function"===typeof d.getAdState&&1===d.getAdState()&&"function"===typeof d.getDuration){if(X)return;try{Number.isFinite(g.duration)?3<d.getDuration()-g.duration&&(X=!0,g.currentTime=g.duration-.5,Y(),b.overridespeeds?g.playbackRate=b.speed:d.setPlaybackRate(b.speed),b.autopausevideos&&W()):setTimeout(function(){Z(h)},50)}catch(Ba){if(!g||(0<Ba.message.indexOf("currentTime")||"IndexSizeError"===Ba.message)&&
g!=a.querySelector("video.html5-main-video"))return}}else Y();0<=b.autofocusevents.indexOf("ads")&&r()}else setTimeout(function(){Z(h)},100)},Y=function(){d.classList.add("ads-removed")},aa=function(){try{var a=d.querySelector("button.ytp-settings-button"),f=d.querySelector("div.ytp-settings-menu");if(!G&&a&&f){ra=new MutationObserver(function(a){a.forEach(function(a){if(null!==a.addedNodes)for(var c=a.addedNodes.length-1;0<=c;c--)if("DIV"===a.addedNodes[c].nodeName&&a.addedNodes[c].classList.contains("ytp-menuitem")&&
0<=a.addedNodes[c].textContent.indexOf(yt.msgs_.YTP_QUALITY_TITLE))a.addedNodes[c].click();else if("DIV"===a.addedNodes[c].nodeName&&a.addedNodes[c].classList.contains("ytp-quality-menu")){c=0;var e=!1,h={"4320p60 8K":"highres","4320p50 8K":"highres","4320p48 8K":"highres","4320p 8K":"highres","4320s 8K":"highres","2880p60 5K":"hd2880","2880p50 5K":"hd2880","2880p48 5K":"hd2880","2880p 5K":"hd2880","2880s 5K":"hd2880","2160p60 4K":"hd2160","2160p50 4K":"hd2160","2160p48 4K":"hd2160","2160p 4K":"hd2160",
"2160s 4K":"hd2160","1440p60 HD":"hd1440","1440p50 HD":"hd1440","1440p48 HD":"hd1440","1440p HD":"hd1440","1440s HD":"hd1440","1080p60 HD":"hd1080","1080p50 HD":"hd1080","1080p48 HD":"hd1080","1080p HD":"hd1080","1080s HD":"hd1080","720p60 HD":"hd720","720p50 HD":"hd720","720p48 HD":"hd720","720p HD":"hd720","720s HD":"hd720","480p":"large","480s":"large","360p":"medium","360s":"medium","240p":"small","240s":"small","144p":"tiny","144s":"tiny"},d=a.addedNodes[c].querySelectorAll("div.ytp-menuitem");
0<d.length&&[b.quality1,b.quality2,b.quality3,b.quality4].forEach(function(b){if(!e){for(;c<d.length;c++)if(b===h[d[c].textContent]){d[c].click();e=!0;break}c=0}});e||d[0].click();G=!0;f.classList.remove("hidden");ra.disconnect()}})});ra.observe(f,{childList:!0,subtree:!0});for(var c=f.querySelectorAll("div.ytp-menuitem"),e,g=c.length-1;0<=g;g--)if(0<=c[g].textContent.indexOf(yt.msgs_.YTP_QUALITY_TITLE)){e=c[g];break}f.classList.add("hidden");setTimeout(function(){f.classList.remove("hidden")},2500);
e?(a.click(),e.click()):a.click()}else if(!G){var q=d.getAvailableQualityLevels();0<=q.indexOf(b.quality1)?d.setPlaybackQuality(b.quality1):0<=q.indexOf(b.quality2)?d.setPlaybackQuality(b.quality2):0<=q.indexOf(b.quality3)?d.setPlaybackQuality(b.quality3):0<=q.indexOf(b.quality4)&&d.setPlaybackQuality(b.quality4)}}catch(Aa){}},D=function(h){try{var f=a.body.classList.contains("enhancer-for-youtube-wide-player");N&&!R&&(R=N.hasAttribute("theater")&&!a.body.classList.contains("enhancer-for-youtube-wide-player"));
if("large"===h||!h&&!f){Ca||Da();var c=a.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]');c?c.parentNode.parentNode.click():N.setAttribute("theater-requested_","");a.body.classList.add("enhancer-for-youtube-wide-player");b.wideplayerviewport&&ea&&(a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):(a.body.classList.add("viewport"),setTimeout(function(){window.scrollTo(window.scrollX,d.getBoundingClientRect().top+
window.scrollY)},80)));!R&&setTimeout(function(){window.postMessage({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:"0"},"*")},250)}else if("default"===h||!h&&f){if(!R){var e=a.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]');e?e.parentNode.parentNode.click():N.removeAttribute("theater-requested_");!e&&window.postMessage({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:"0"},"*")}a.body.classList.remove("enhancer-for-youtube-wide-player",
"viewport","_viewport_");R=!1}}catch(B){}0<=b.autofocusevents.indexOf("size")&&r()},W=function(){if(b.ignoreplaylists&&0<a.location.href.indexOf("list=")||!b.pauseforegroundtab&&!ja&&!a.hidden)b.selectquality&&(n?Q():aa()),a.hidden||(L=!0);else{a.hidden||(L=!0);clearInterval(P);try{b.disablepreloading?(d.stopVideo(),d.addEventListener("onStateChange",function B(a){if(1===a){d.removeEventListener("onStateChange",B);b.selectquality&&n&&Q();try{d[b.removeannotations?"unloadModule":"loadModule"]("annotations_module"),
d.setAttribute("annotations-module-loaded",b.removeannotations?0:1),"undefined"!==typeof ytplayer&&ytplayer.config&&ytplayer.config.args&&ytplayer.config.args.start&&d.seekTo(parseInt(ytplayer.config.args.start,10))}catch(q){}}})):d.pauseVideo()}catch(c){var h,f=0;P=setInterval(function(){try{d&&"function"===typeof d.getPlayerState||(f++,"video"===A?M():pa()),h=d.getPlayerState(),a.hidden?-1!==h&&b.disablepreloading?d.stopVideo():2===h||b.disablepreloading||d.pauseVideo():-1!==h&&5!==h&&b.pauseforegroundtab&&
b.disablepreloading?d.stopVideo():2!==h&&b.pauseforegroundtab&&!b.disablepreloading?(-1!==h&&5!==h||d.playVideo(),3!==h&&d.pauseVideo()):clearInterval(P)}catch(e){200<f&&clearInterval(P),d=!1}},50)}r()}},Ea=function(a){if(a.ctrlKey&&!a.shiftKey&&"function"===typeof d.getPlayerState&&0<d.getPlayerState()||"I"===a.target.nodeName){a.preventDefault();t=b.speed;try{b.overridespeeds?g.playbackRate=t:d.setPlaybackRate(t),"I"===a.target.nodeName?u.textContent=C.speed+" x"+t:(J.textContent="x"+t,oa())}catch(f){}0<=
b.autofocusevents.indexOf("speed")&&r()}},oa=function(){J.setAttribute("style","display:block!important");clearTimeout(Fa);Fa=setTimeout(function(){J.setAttribute("style","display:none!important")},1500)},wa=function(){v.style.marginLeft="-"+parseInt(window.getComputedStyle(k,null).getPropertyValue("width"),10)/2+"px"},I=function(a,f){a.addEventListener("mouseenter",function(a){b.toolbartooltips&&(u.textContent=f,u.style.left=4+Math.floor(a.target.getBoundingClientRect().left)-parseInt(window.getComputedStyle(u,
null).getPropertyValue("width"),10)/2+"px",u.classList.add("visible"))});a.addEventListener("mouseleave",function(){u.classList.remove("visible")})},Qa=function(){try{y.max=g.duration,y.value=g.currentTime}catch(h){}},Ga=function(a){if("I"===a.target.nodeName||a.ctrlKey)if(a.preventDefault(),!n){try{if(b.overridespeeds){var f=g.playbackRate;0<a.deltaY?(f=parseFloat((f-b.speedvariation).toFixed(2)),0>=f&&(f=b.speedvariation),g.playbackRate=f):0>a.deltaY&&(f=parseFloat((f+b.speedvariation).toFixed(2)),
g.playbackRate=f)}else{var c=d.getAvailablePlaybackRates();f=d.getPlaybackRate();var e=c.indexOf(f);0<a.deltaY&&0<e?(f=c[e-1],d.setPlaybackRate(f)):0>a.deltaY&&e<c.length-1&&(f=c[e+1],d.setPlaybackRate(f))}t=f;"I"===a.target.nodeName?u.textContent=C.speed+" x"+f:(J.textContent="x"+f,oa())}catch(B){}0<=b.autofocusevents.indexOf("speed")&&r()}},Ha=function(a){if("I"===a.target.nodeName||a.ctrlKey&&a.shiftKey){a.preventDefault();try{var f=""===(g.style.filter?g.style.filter:g.style["-webkit-filter"])?
!1:!0;g.style["-webkit-filter"]=f?"":b.filter;g.style.filter=f?"":b.filter;k.querySelector("i.filters").parentNode.classList[f?"remove":"add"]("active")}catch(c){}0<=b.autofocusevents.indexOf("filters")&&r()}},qa=function(b){b.querySelector("#enhancer-for-youtube-player-info")||(a.querySelector("#enhancer-for-youtube-player-info")||(J=a.createElement("div"),J.id="enhancer-for-youtube-player-info"),b.appendChild(J))},Ra=function(){if(!v){w=a.createElement("div");v=a.createElement("div");k=a.createElement("div");
u=a.createElement("div");var h=a.createDocumentFragment(),f=a.createElement("ul"),c=a.createElement("li"),e=a.createElement("i");w.id="enhancer-for-youtube-background";w.style.visibility="hidden";w.addEventListener("click",function(){ba()});h.appendChild(w);v.id="enhancer-for-youtube-toolbar-wrapper";k.id="enhancer-for-youtube-toolbar";u.id="enhancer-for-youtube-tooltip";h.appendChild(u);k.style.visibility="hidden";b.transparency&&k.classList.add("transparency");b.slideeffect&&k.classList.add("slide-effect");
c.dataset.name=e.className="message";c.appendChild(e);e=a.createElement("i");e.className="badge";c.appendChild(e);c.addEventListener("click",function(){window.postMessage({enhancerforyoutube:"show-message"},"*")});I(c,C.message);f.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="clean";c.appendChild(e);c.addEventListener("click",function(){sa=!0;X=!1;Z()});c.addEventListener("contextmenu",function(a){a.preventDefault();d||M();try{var c=d.getAttribute("annotations-module-loaded");
d["1"===c?"unloadModule":"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded","1"===c?0:1);0<=b.autofocusevents.indexOf("annotations")&&r()}catch(Aa){}return!1});I(c,C.remove_ads);f.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="cinema";c.appendChild(e);c.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-cinema-mode")?ba():na()});I(c,C.cinema_mode);f.appendChild(c);c=a.createElement("li");e=a.createElement("i");
c.dataset.name=e.className="resize";c.appendChild(e);c.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-pinned-player")||(a.body.classList.contains("enhancer-for-youtube-pinned-player")&&(a.body.classList.remove("enhancer-for-youtube-pinned-player"),window.scrollTo(0,0)),D())});c.addEventListener("contextmenu",function(a){a.preventDefault();try{window.scrollTo(window.scrollX,l.getBoundingClientRect().top+
window.scrollY)}catch(q){}return!1});I(c,C.resize_player);f.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="detach";c.appendChild(e);c.addEventListener("click",function(){var b=a.location.href.match(/v=(.+)&?/)[1]+"?autoplay=1",c=a.location.href.match(/list=(.+)&?/);c&&(b+="&list="+c[1]);try{d.pauseVideo();var e=d.getCurrentTime();e&&(b+="&start="+parseInt(e,10))}catch(Za){}window.postMessage({enhancerforyoutube:"detach",params:b},"*")});I(c,C.detach_player);
f.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="loop";c.appendChild(e);c.addEventListener("click",function(){if(Ia)ya(this);else{Ia=!0;m=a.createElement("link");m.rel="stylesheet";m.href=O+"/vendor/jquery/jquery-ui.min.css";a.head.appendChild(m);var c=this,e=a.createElement("script");e.src=O+"/vendor/jquery/jquery-3.3.1.min.js";e.onload=function(){e=a.createElement("script");e.src=O+"/vendor/jquery/jquery-ui.min.js";e.onload=function(){ya(c)};a.head.appendChild(e)};
a.head.appendChild(e)}0<=b.autofocusevents.indexOf("loop")&&r()});I(c,C.loop_video);f.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="speed";c.appendChild(e);n&&c.classList.add("not-allowed");c.addEventListener("click",Ea);c.addEventListener("wheel",Ga);c.addEventListener("mouseenter",function(a){if(b.toolbartooltips){var c="";try{c=" x"+g.playbackRate}catch(Aa){}u.textContent=C.speed+c;u.style.left=4+Math.floor(a.target.getBoundingClientRect().left)-parseInt(window.getComputedStyle(u,
null).getPropertyValue("width"),10)/2+"px";u.classList.add("visible")}});c.addEventListener("mouseleave",function(){u.classList.remove("visible")});f.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="filters";c.appendChild(e);n&&c.classList.add("not-allowed");c.addEventListener("click",Ha);c.addEventListener("contextmenu",function(b){b.preventDefault();this.classList.contains("not-allowed")||(this.hasAttribute("ui")?a.querySelector("#enhancer-for-youtube-filters").classList.toggle("hidden"):
window.postMessage({enhancerforyoutube:"filters"},"*"));return!1});I(c,C.filters);f.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="script";c.appendChild(e);c.addEventListener("click",function(){r();window.postMessage({enhancerforyoutube:"custom-script"},"*")});I(c,C.custom_script);f.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="options";c.appendChild(e);c.addEventListener("click",function(){r();window.postMessage({enhancerforyoutube:"show-options"},
"*")});I(c,C.options);f.appendChild(c);k.appendChild(f);v.appendChild(k);h.appendChild(v);y=a.createElement("progress");y.id="enhancer-for-youtube-progress";y.max=1;y.value=0;y.addEventListener("click",function(a){g&&(g.currentTime=Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth));r()});y.addEventListener("mouseenter",function(){K.classList.add("visible")});y.addEventListener("mouseleave",function(){K.classList.remove("visible")});y.addEventListener("mousemove",function(a){g&&(K.textContent=
ma(Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth)),K.style.left=a.pageX-parseInt(window.getComputedStyle(K,null).getPropertyValue("width"),10)/2-6+"px")});h.appendChild(y);K=a.createElement("div");K.id="enhancer-for-youtube-progress-tooltip";h.appendChild(K);f=a.createElement("div");f.id="enhancer-for-youtube-unpin-player";f.addEventListener("click",function(){a.body.classList.remove("enhancer-for-youtube-pinned-player")});h.appendChild(f);a.body.appendChild(h);setTimeout(function(){ka();
wa();w.style.visibility="";k.style.visibility=""},500)}},Da=function(){var b=a.documentElement.clientWidth,f=a.documentElement.clientHeight,c=window.innerWidth,e=a.querySelector("ytd-masthead");e=e?parseInt(window.getComputedStyle(e,null).getPropertyValue("height"),10):56;var d=k?parseInt(window.getComputedStyle(k,null).getPropertyValue("height"),10)+1:30;if(parseInt(16/9*(f-e-d),10)>b){e=parseInt(b/(16/9),10);f=b;var g=e;ea=!1}else e=parseInt(f-e-d,10),b=parseInt(16/9*e,10),c-=c-b,g=window.screen.height===
f?f-12:f,f=parseInt(16/9*g,10),ea=!0;d=parseInt(c/(16/9),10);var l=parseInt(b/2,10);var n=parseInt(c/2,10);var m=parseInt(f/2,10);var p=a.createElement("style");p.type="text/css";p.textContent="body.enhancer-for-youtube-wide-player ytd-watch[theater] #player,body.enhancer-for-youtube-wide-player ytd-watch[theater] embed#movie_player,body.enhancer-for-youtube-wide-player ytd-watch[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player ytd-watch[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
e+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch[theater] #player,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch[theater] embed#movie_player,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
g+"px !important}body.enhancer-for-youtube-wide-player ytd-watch[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player ytd-watch[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+b+"px !important;margin-left:-"+l+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) ytd-watch[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+
f+"px !important;margin-left:-"+m+"px !important}body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch[theater] #player,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch[theater] embed#movie_player,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
d+"px !important}body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch[theater] #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch[theater] #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+c+"px !important;margin-left:-"+n+"px !important}";a.head.appendChild(p);Ca=!0},Ja=function(){window.IntersectionObserver&&!l.hasAttribute("io")&&(l.setAttribute("io",1),ta=new IntersectionObserver(function(d){if((0===
d[0].intersectionRatio&&!a.body.classList.contains("enhancer-for-youtube-pinned-player")&&0<window.scrollY||0<d[0].intersectionRatio&&.12>d[0].intersectionRatio)&&window.scrollY>l.offsetHeight-100&&S()){a.body.classList.add("enhancer-for-youtube-pinned-player");try{g.style.top=""}catch(f){}0<=b.autofocusevents.indexOf("pin")&&r()}else 0!==d[0].intersectionRatio&&(a.body.classList.remove("enhancer-for-youtube-pinned-player"),n||Sa())},{threshold:.12}),ta.observe(l))},Sa=function(){setTimeout(function(){try{if(!a.body.classList.contains("enhancer-for-youtube-pinned-player")){var b=
window.getComputedStyle(l).height,f=window.getComputedStyle(d).height,c=window.getComputedStyle(g).height;f!==b?(d.style.width=window.getComputedStyle(l).width,d.style.height=b,d.style.width="",d.style.height=""):c!==b&&(g.style.width=window.getComputedStyle(l).width,g.style.height=b,g.style.top="")}}catch(e){}},50)},Ka=function(){(new MutationObserver(function(b){b.forEach(function(b){try{b.target.hasAttribute("theater-requested_")||b.target.hasAttribute("theater")||(a.body.classList.remove("enhancer-for-youtube-wide-player"),
R=!1)}catch(c){}})})).observe(N,{attributes:!0})},Ta=function(){ia=setInterval(function(){try{if("function"!==typeof d.getPlayerState&&M(),0===d.getPlayerState()&&(clearInterval(ia),!k.querySelector("i.loop").parentNode.classList.contains("active"))){var b=a.querySelector("ytd-watch ytd-playlist-panel-renderer ytd-playlist-panel-video-renderer[selected]");if(b){var f=b.nextElementSibling;f&&(a.location.href=f.querySelector("a").href)}}}catch(c){}},5E3)},ua=function(){var d=b.backgroundcolor.replace("#",
""),f=parseInt(d.substring(0,2),16),c=parseInt(d.substring(2,4),16);d=parseInt(d.substring(4,6),16);m=a.createElement("style");m.type="text/css";m.textContent="body.enhancer-for-youtube-cinema-mode.enhancer-for-youtube-wide-player ytd-watch .html5-video-player{background-color:rgba("+f+","+c+","+d+","+b.backgroundopacity/100+")}";a.head.appendChild(m)},r=function(){try{a.activeElement.blur(),d.focus({preventScroll:!0})}catch(h){}},pa=function(){d=a.querySelector("#c4-player")},M=function(){d=a.querySelector("#movie_player")},
S=function(){return/^https:\/\/www\.youtube\.com\/watch\?(.*&)?v=/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/c\/.*\/live/.test(a.location.href)},fa=function(b,a){var c=parseInt(b.slice(1),16),e=0>a?0:255,d=0>a?-1*a:a,f=c>>16,h=c>>8&255;c&=255;return"#"+(16777216+65536*(Math.round((e-f)*d)+f)+256*(Math.round((e-h)*d)+h)+(Math.round((e-c)*d)+c)).toString(16).slice(1)},La=function(){var d=a.createElement("style"),f=b.toolbarbackgroundcolor.replace("#",""),c=parseInt(f.substring(0,2),16),
e=parseInt(f.substring(2,4),16);f=parseInt(f.substring(4,6),16);d.type="text/css";d.textContent="#enhancer-for-youtube-toolbar,body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-toolbar-wrapper:hover #enhancer-for-youtube-toolbar{background-color:"+b.toolbarbackgroundcolor+";border-top:0.1em solid "+b.toolbarbordercolor+";border-right:0.1em solid "+b.toolbarbordercolor+";border-left:0.1em solid "+b.toolbarbordercolor+";color:"+b.toolbarcolor+"}#enhancer-for-youtube-toolbar i{color:"+b.toolbarcolor+
" !important}#enhancer-for-youtube-toolbar.transparency{opacity:"+b.toolbaropacity/100+"}#enhancer-for-youtube-slider.ui-widget-content{background-image:none;background-color:"+b.toolbarbackgroundcolor+";border:0.1em solid "+b.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-widget-header{background-image:none;background-color:"+fa(b.toolbarbackgroundcolor,-.1)+"}#enhancer-for-youtube-slider .ui-state-default{background-image:none;background-color:"+fa(b.toolbarbackgroundcolor,-.1)+";border:0.1em solid "+
b.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-state-hover,#enhancer-for-youtube-slider .ui-state-focus{background-image:none;background-color:"+fa(b.toolbarbackgroundcolor,-.15)+";border:0.1em solid "+fa(b.toolbarbordercolor,-.15)+"}#enhancer-for-youtube-toolbar .start-end{background-color:rgba("+c+","+e+","+f+",0.85)}#enhancer-for-youtube-filters{background-color:"+b.toolbarbackgroundcolor+" !important;border:0.1em solid "+b.toolbarbordercolor+" !important;color:"+b.toolbarcolor+" !important}#enhancer-for-youtube-unpin-player,#enhancer-for-youtube-filters button.close{color:"+
b.toolbarcolor+" !important}";a.head.appendChild(d)},Ua=function(){Ma=setInterval(function(){try{(a.activeElement.classList.contains("ytp-progress-bar")||a.activeElement.classList.contains("ytp-volume-panel"))&&r()}catch(h){}},3E3)},Va=function(){clearInterval(Ma)},Wa=function(a){try{100<=a&&setTimeout(function(){d.nextVideo()},2E3)}catch(f){}},Na=function(a){1===a&&(d.removeEventListener("onStateChange",Na),g&&b.overridespeeds?g.playbackRate=t:d.setPlaybackRate(t))},Xa=function(h){try{b.pausevideos&&
!a.hidden&&1===h&&window.postMessage({enhancerforyoutube:"pause-videos"},"*"),b.autopausevideos&&!L&&1===h&&W(),b.selectquality&&!G&&1===h&&aa(),0===h&&"video"===A&&setTimeout(function(){d.classList.contains("ended-mode")&&(y.value=y.max)},500)}catch(f){}},Ya=function(h){try{b.pausevideos&&!a.hidden&&1===h&&window.postMessage({enhancerforyoutube:"pause-videos"},"*");if(b.removeads&&1===h&&0>ha.indexOf(z)||sa&&1===h)"video"===A?Z(h):(g.currentTime=g.duration,Y());0===h&&(X=!1,d.addEventListener("onStateChange",
Na),Y())}catch(f){}},T=function(){m||(m=a.createElement("link"),m.rel="stylesheet",m.href=O+"/youtube-polymer.css",a.head.appendChild(m),m=a.createElement("style"),m.type="text/css",m.textContent="#enhancer-for-youtube-background{background-color:"+b.backgroundcolor+"}body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-background{opacity:"+b.backgroundopacity/100+";visibility:visible}",a.head.appendChild(m),ua(),La());A=d=l=g=sa=X=G=!1;if(S())if(A="video",M(),d)try{z=d.getVideoData().author}catch(h){(z=
a.querySelector("#upload-info #owner-name"))&&(z=z.textContent.trim())}else z="";else if(/^https:\/\/www\.youtube\.com\/channel\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/channel\/[^\/]+\/featured/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+\/featured/.test(a.location.href))if(A="channel",pa(),d)try{z=d.getVideoData().author}catch(h){(z=a.querySelector("h1 #channel-title"))&&(z=z.textContent.trim())}else z=
"";if(A&&d){l=d.parentNode;"EMBED"===d.nodeName?(n=!0,"video"===A&&0<a.location.href.indexOf("list=")&&Ta(),a.body.classList.add("flash-player-loaded")):((g=d.querySelector("video.html5-main-video"))&&g.addEventListener("timeupdate",Qa),d.addEventListener("onAdStateChange",Ya),d.addEventListener("onStateChange",Xa),d.addEventListener("onError",Wa),l.addEventListener("mouseleave",Va),l.addEventListener("mouseenter",Ua),l.addEventListener("click",Ea),l.addEventListener("wheel",Ga),l.addEventListener("click",
Ha),setTimeout(function(){try{g&&b.overridespeeds?(g.playbackRate=t,g.defaultPlaybackRate=t):d.setPlaybackRate(t)}catch(h){}},500));"video"===A?(b.removeads&&0>ha.indexOf(z)&&(n||!n&&1===d.getAdState())?Z():b.autopausevideos&&(n||!n&&1===d.getPlayerState())?W():b.selectquality&&(n?Q():aa()),b.removeads&&0>ha.indexOf(z)&&Y(),b.cinemamode?setTimeout(function(){na();!b.cinemamodewideplayer&&b.wideplayer&&D("large")},b.cinemamodewideplayer||b.wideplayer?1200:1):b.wideplayer&&setTimeout(function(){D("large")},
1200),v?(v.style.display="",w.style.display=""):Ra(),b.pinnedplayer&&(Ja(),a.body.classList.add(b.pinnedplayersize,b.pinnedplayerposition)),b.expanddescription&&setTimeout(function(){try{a.querySelector("ytd-video-secondary-info-renderer.ytd-watch paper-button#more").click()}catch(h){}},2E3),0<a.location.href.indexOf("list=")&&setTimeout(function(){try{var b=a.querySelector("ytd-playability-error-supported-renderers");b&&240<=parseInt(window.getComputedStyle(b,null).getPropertyValue("height"),10)&&
a.querySelector("ytd-watch ytd-playlist-panel-renderer ytd-playlist-panel-video-renderer[selected]").nextElementSibling.querySelector("a").click()}catch(f){}},2E3)):"channel"===A&&(b.autopausevideos?W():b.selectquality&&(n?Q():aa()));qa(n?l:d);b.controlvolume&&l.addEventListener("wheel",za);b.enablefilters&&g&&(g.style["-webkit-filter"]=b.filter,g.style.filter=b.filter);try{b.defaultvolume&&d.setVolume(b.volume),d[b.removeannotations?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",
b.removeannotations?0:1)}catch(h){}b.pausevideos&&!a.hidden&&window.postMessage({enhancerforyoutube:"pause-videos"},"*")}};window.EnhancerForYouTube=!0;var O=EnhancerForYouTubeResources,b=EnhancerForYouTubePreferences,C=EnhancerForYouTubeMessages,ja=a.hidden,N=a.querySelector("ytd-watch"),l,d,g,w,v,k,u,J,Fa,F,xa,y,K,L,ta,m,Ia,n,Ca,ea,A,P,Ma,ia,V,Oa,H,p,x,R,sa,X,G,z,ha=""!==b.whitelist?b.whitelist.split(","):[],t=b.speed,U,ra;(new MutationObserver(function(h){h.forEach(function(f){if(null!==f.addedNodes)for(var c=
f.addedNodes.length-1;0<=c;c--)if(!n&&f.addedNodes[c].id&&("movie_player"===f.addedNodes[c].id||"c4-player"===f.addedNodes[c].id)){if("EMBED"===f.addedNodes[c].nodeName){try{d.stopVideo()}catch(B){}l=f.addedNodes[c].parentNode;qa(l);k&&(k.querySelector(".speed").classList.add("not-allowed"),k.querySelector(".filters").classList.add("not-allowed"));"complete"===a.readyState&&T()}}else if("YTD-WATCH"===f.addedNodes[c].nodeName)N=f.addedNodes[c],Ka();else if("VIDEO"===f.addedNodes[c].nodeName&&g&&g!=
d.querySelector("video.html5-main-video"))g=f.addedNodes[c],setTimeout(function(){L=!1;T();try{g&&b.overridespeeds?(g.playbackRate=t,g.defaultPlaybackRate=t):d.setPlaybackRate(t)}catch(B){}},650);else if("YTD-VIDEO-SECONDARY-INFO-RENDERER"===f.addedNodes[c].nodeName&&b.expanddescription)try{f.addedNodes[c].querySelector("ytd-video-secondary-info-renderer.ytd-watch paper-button#more").click()}catch(B){}else if("YT-SORT-FILTER-SUB-MENU-RENDERER"===f.addedNodes[c].nodeName&&b.newestcomments)setTimeout(function(){try{a.querySelector("ytd-comments yt-sort-filter-sub-menu-renderer a.yt-dropdown-menu:last-of-type").click(),
U=!0}catch(B){}},500);else if("YTD-COMMENT-THREAD-RENDERER"===f.addedNodes[c].nodeName&&b.newestcomments&&!U&&20===f.addedNodes[c].parentNode.children.length)setTimeout(function(){try{!U&&a.querySelector("ytd-comments yt-sort-filter-sub-menu-renderer a.yt-dropdown-menu:last-of-type").click(),U=!0}catch(B){}},4E3);else if(b.disableautoplay&&"YTD-COMPACT-AUTOPLAY-RENDERER"===f.addedNodes[c].nodeName)try{var e=f.addedNodes[c].querySelector("#head > paper-toggle-button");(e.checked||e.active)&&e.click()}catch(B){}})})).observe(a.body,
{childList:!0,subtree:!0});N&&Ka();window.addEventListener("yt-history-load",E);window.addEventListener("yt-navigate-start",E);window.addEventListener("yt-navigate-finish",function(a){T()});(a.querySelector("video.html5-main-video")||a.querySelector("#movie_player")||a.querySelector("#c4-player"))&&T();a.addEventListener("visibilitychange",function f(){a.hidden||(L||T(),a.removeEventListener("visibilitychange",f),setTimeout(function(){L=!0;ja=!1},1500))});window.addEventListener("load",function c(){window.removeEventListener("load",
c);setTimeout(function(){m||T()},250)});b.executescript&&window.postMessage({enhancerforyoutube:"custom-script"},"*");b.theme=b.theme.replace(".css","-polymer.css");"default"!==b.theme&&((E=a.head.querySelector("#enhancer-for-youtube-theme"))?E.hasAttribute("href")&&0>E.href.indexOf(b.theme)&&E.setAttribute("href",O+"/vendor/themes/"+b.theme):"custom"===b.theme?window.postMessage({enhancerforyoutube:"custom-theme"},"*"):(E=a.createElement("link"),E.id="enhancer-for-youtube-theme",E.rel="stylesheet",
E.href=O+"/vendor/themes/"+b.theme,a.head.appendChild(E)));window.addEventListener("message",function(c){if(c.data.enhancerforyoutube&&"pause-video"===c.data.enhancerforyoutube)try{d.pauseVideo()}catch(q){}else if(c.data.enhancerforyoutube&&"preference-changed"===c.data.enhancerforyoutube){var e=c.data.value;switch(c.data.name){case "autofocusevents":case "autopausevideos":case "controlvolumealtkey":case "disableautoplay":case "disablepreloading":case "ignoreplaylists":case "newestcomments":case "overridespeeds":case "pauseforegroundtab":case "pausevideos":case "removeads":case "speedvariation":case "toolbartooltips":case "volumevariation":b[c.data.name]=
e;break;case "backgroundcolor":b.backgroundcolor=e;w&&(w.style.backgroundColor=e);ua();break;case "backgroundopacity":b.backgroundopacity=e;w&&(w.style.opacity=e/100);ua();break;case "cinemamode":b.cinemamode=e;S()&&(e?na():ba());break;case "cinemamodewideplayer":b.cinemamodewideplayer=e;S()&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")&&(e?D("large"):D("default"));break;case "controlvolume":b.controlvolume=e;if(l)l[e?"addEventListener":"removeEventListener"]("wheel",za);break;case "customtheme":if("default"!==
b.theme)try{a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme"))}catch(q){}c=a.createElement("style");c.type="text/css";c.id="enhancer-for-youtube-theme";c.textContent=e;a.head.appendChild(c);va(e);break;case "defaultvolume":b.defaultvolume=e;try{e&&d.setVolume(b.volume)}catch(q){}break;case "enablefilters":b.enablefilters=e;try{g.style["-webkit-filter"]=e?b.filter:"",g.style.filter=e?b.filter:""}catch(q){}break;case "executescript":b.executescript=e;b.executescript&&window.postMessage({enhancerforyoutube:"custom-script"},
"*");break;case "expanddescription":b.expanddescription=e;try{a.querySelector("ytd-video-secondary-info-renderer.ytd-watch paper-button#"+(e?"more":"less")).click()}catch(q){}break;case "filter":b.filter=e;if(!a.hidden)try{g.style["-webkit-filter"]=e,g.style.filter=e,k.querySelector("i.filters").parentNode.classList.add("active")}catch(q){}break;case "message":b.message=e;ka();break;case "pinnedplayer":b.pinnedplayer=e;l&&l.removeAttribute("io");if(e)a.body.classList.add(b.pinnedplayersize,b.pinnedplayerposition),
S()&&Ja();else try{a.body.classList.remove("enhancer-for-youtube-pinned-player",b.pinnedplayersize,b.pinnedplayerposition),ta.disconnect()}catch(q){}break;case "pinnedplayerposition":a.body.classList.add(e);a.body.classList.remove(b.pinnedplayerposition);b.pinnedplayerposition=e;break;case "pinnedplayersize":a.body.classList.add(e);a.body.classList.remove(b.pinnedplayersize);b.pinnedplayersize=e;break;case "quality1":case "quality2":case "quality3":case "quality4":case "selectquality":b[c.data.name]=
e;if("quality1"===c.data.name||b.selectquality)e=(new Date).getTime(),localStorage["yt-player-quality"]='{"data":"'+b.quality1+'","expiration":'+(e+2592E6)+',"creation":'+e+"}";A&&b.selectquality&&(G=!1,n?Q():aa());break;case "removeannotations":b.removeannotations=e;try{d[e?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",e?0:1)}catch(q){}break;case "slideeffect":b.slideeffect=e;if(k)k.classList[e?"add":"remove"]("slide-effect");break;case "speed":b.speed=
t=e;try{0>[.25,.5,1,1.25,1.5,2].indexOf(e)?(g.playbackRate=e,g.defaultPlaybackRate=e):d.setPlaybackRate(e)}catch(q){}break;case "theme":try{if("default"!==b.theme&&a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme")),b.theme=e.replace(".css","-polymer.css"),"custom"===e)window.postMessage({enhancerforyoutube:"custom-theme"},"*");else if("default"!==e){var m=a.createElement("link");m.id="enhancer-for-youtube-theme";m.rel="stylesheet";m.href=O+"/vendor/themes/"+b.theme;a.head.appendChild(m)}}catch(q){}va();
break;case "toolbarbuttons":b.toolbarbuttons=e;k&&ka();break;case "toolbarbackgroundcolor":case "toolbarbordercolor":case "toolbarcolor":case "toolbaropacity":b[c.data.name]=e;La();break;case "transparency":b.transparency=e;if(k)k.classList[e?"add":"remove"]("transparency");break;case "volume":b.volume=e;try{d.setVolume(e)}catch(q){}break;case "whitelist":ha=""!==e?e.split(","):[];break;case "wideplayer":b.wideplayer=e;S()&&(e?D("large"):D("default"));break;case "wideplayerviewport":(b.wideplayerviewport=
e,e)?e&&ea&&(a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):a.body.classList.contains("enhancer-for-youtube-wide-player")&&(a.body.classList.add("viewport"),setTimeout(function(){window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},80))):a.body.classList.remove("viewport","_viewport_")}}});window.addEventListener("error",function(b){setTimeout(function(){n||!d||
d.querySelector("video")||a.location.reload()},a.documentElement.hasAttribute("flash-player-for-youtube")||a.documentElement.hasAttribute("youtube-flash-player")?3E3:1)});window.addEventListener("resize",function(a){clearTimeout(Oa);Oa=setTimeout(Da,500)});a.addEventListener("keydown",function(a){27===a.keyCode&&d&&!d.classList.contains("ytp-fullscreen")&&w&&w.click()})}})(document);